### ISSUE TITLE
Can the data_cmu.npz file be used for custom dataset

### ISSUE THREAD

**Issue by UsamaShaikh1** [BrianG13/FLEX#14]
Hello, Thanks for excellent work. I am trying your codebase with my custom dataset and was confused regarding the file which contains the data for discriminator. Can that file be reused for any custom dataset and if not, how can this data be created for a custom dataset
@BrianG13

**Comment by BrianG13** [comment]
If your output is the same as the current you can use the current file, but if you want to use a different number of joints or joint hierarchy you will need to create your own.

The discriminator inputs are the joint rotations (quaternions format), the idea is that discriminator helps the quaternions estimator model to produce "natural and human" movements while having GT references of those, it don't have to be the same datasets as used for training the 3D pose

**Comment by UsamaShaikh1** [comment]
Thanks for your reply, i observed that the shape for the data_cmu was (frame,12,4) i can understand that 4 dimensions are for quaternion angles but what specifically does the 12 represent as the human 3.6m dataset you are using consists of 20 joints. @BrianG13

**Comment by UsamaShaikh1** [comment]
I also noticed that cmu dataset is not being used for training either, is it sue to the code being incomplete or some other reason

**Comment by BrianG13** [comment]
Hi @UsamaShaikh1 our best model (lowest MPJPE on H36M) is not trained with the discriminator, so no need for the data_cmu.

But for in-the-wild data the model trained with the discriminator performs better.
