### ISSUE TITLE
Confidence score is false

### ISSUE THREAD

**Issue by UsamaShaikh1** [BrianG13/FLEX#15]
Hi, i read your paper and came across that confidence score was also used, however in the config file confidence is set to false. Has the codebase not provided the use of confidence score, if it has how can we use it

**Comment by BrianG13** [comment]
Our published model weights is without using the confidence score, but if you want to train using those it is very simple.

Just change the config json here: https://github.com/BrianG13/FLEX/blob/main/config_zoo/default.json#L18 to True and it should work :)

What is the data you are using to train your model?
