### ISSUE TITLE
rigged skeleton for viz

### ISSUE THREAD

**Issue by Nyquixt** [BrianG13/FLEX#2]
Hey,

Thanks for the amazing work. I wonder where I can get the rigged skeleton model to visualize the results in Blender or whether we could create it manually. I'm relatively new to the field.

Best,
K

**Comment by BrianG13** [comment]
The visualizations are created using Blender software.
Our model output is `.bvh` files than can be imported to Blender.
I can attach an example of a `.bvh` file if this will help you

**Comment by Nyquixt** [comment]
Yes please. Thank you very much!

**Comment by BrianG13** [comment]
![image](https://user-images.githubusercontent.com/51123168/160846033-a7277794-725a-41bc-8ed2-e31903259d53.png)

Attached a .zip file with the .bvh file inside (github does not allow to upload .bvh files)
[pose.zip](https://github.com/BrianG13/FLEX/files/8389869/pose.zip)
