### ISSUE TITLE
Demo Script

### ISSUE THREAD

**Issue by anas-zafar** [BrianG13/FLEX#7]
Thank you for the amazing work! I want to run inference using videos from multiple views. Is there a demo script that I can use? @BrianG13 Thanks

**Comment by anas-zafar** [comment]
I see that you have created visualization.py for visualization of 2D and corresponding 3D poses. Can you please guide me how to use it? `visualize_2d_and_3d(gt_pose_2d, gt_pose_3d, fake_pose_2d, fake_pose_3d, save_path)`  what are fake_pose_2d and 3d referring to?

**Comment by BrianG13** [comment]
Hi @anas-zafar ,
Sorry for the delay on reply, I was in vacation
Do you still need my support?

**Comment by felipe-parodi** [comment]
Following up on this, is there a demo script to run inference using videos from multiple views?
