### ISSUE TITLE
Did you implement TesseTrack paper?

### ISSUE THREAD

**Issue by mnauf** [BrianG13/FLEX#8]
Did you implement the TesseTrack paper? If yes, can you put that in your repo too?

"For comparing with the best available method, we have chosen the current state-of-the-art multi-view algorithm of Iskakov et al. [30] (TesseTrack [60] is marginally better, but it does not provide code). Since their algorithm is not epfree, we imitate parameter estimation by running a controlled perturbation of the camera parameters. We re-train their method with distorted data to simulate an environment where camera distortion parameters are unknown."

**Comment by BrianG13** [comment]
Nope.
As you can see from the paper, because TesseTrack did not provide any code, we used Iskakov Et al. paper to compare the different noises on camera parameters estimations.
